spring:
  application:
    name: ranking-service # this name has to EXACTLY match the .yml file name in config service
  cloud:
    config:
      import: optional:configserver:http://localhost:8888
  ranking:
    email:
      service:
        url: https://bite-scout-ranking-264767797819.us-central1.run.app/api/ranking