spring:
  application:
    name: discovery-service # this name has to EXACTLY match the .yml file name in config service
  cloud:
    config:
      import: optional:configserver:http://localhost:8888
