spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost:8080"
              - "http://localhost:5174"
              - "http://localhost:8222"   # React app URL
              - "https://bitescout.netlify.app"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "Authorization"
              - "Content-Type"
              - "X-Requested-With"
            allowCredentials: true
            maxAge: 3600
  application:
    name: gateway-service # this name has to EXACTLY match the .yml file name in config service
  config:
      import: optional:configserver:http://localhost:8888
