server:
  port: 8090
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/notifications
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: reservationGroup, offerGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: reservationStatusMessage:com.bitescout.app.notificationservice.kafka.reservation.ReservationStatusMessage,specialOfferMessage:com.bitescout.app.notificationservice.kafka.offer.SpecialOfferMessage
  mail:
    host: smtp.gmail.com
    port: 1025
    username: infobitescout@gmail.com
    password: m1KvyJZBwhC119W
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
application:
  config:
    restaurants-url: http://localhost:8222/api/v1/restaurants
    users-url: http://localhost:8222/api/v1/users