server:
  port: 8030
spring:
  data:
    mongodb:
      username: user
      password: password
      host: localhost
      port: 27017
      database: reviews
      authentication-database: admin

application:
  config:
    users-url: http://localhost:8222/v1/users