server:
  port: 8070
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/users
    username: user
    password: password
  sql:
    init:
      mode: always  # Will run SQL files on every startup
      data-locations: classpath:db/data.sql
  jpa:
    hibernate:
      ddl-auto: create
      format_sql: true
    show-sql: true
    database: postgresql
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  file:
    storage:
      service:
        url: https://gcloud-storage-service-264767797819.us-central1.run.app/api/storage/user-picture/
  email:
    storage:
      service:
        url: https://gcloud-storage-service-264767797819.us-central1.run.app/api/storage/